// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQpM4sfSy2XHiUAhjGE7yvRXVG8T6IM2o',
    appId: '1:238114527059:android:a6b3201c57d8c90fb0b3a6',
    messagingSenderId: '238114527059',
    projectId: 'daily-reminders-2a399',
    storageBucket: 'daily-reminders-2a399.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbbUCIuQ575EhBWOQoN16gKw5uJ2zkAu8',
    appId: '1:238114527059:ios:f1b4a4e6e05bc092b0b3a6',
    messagingSenderId: '238114527059',
    projectId: 'daily-reminders-2a399',
    storageBucket: 'daily-reminders-2a399.firebasestorage.app',
    iosBundleId: 'com.daily.reminders.flutterReminders',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBev5NU_nXDfiuGRIz9sWi0xU-_h2XQT6g',
    appId: '1:238114527059:web:4c30f027fc2c8707b0b3a6',
    messagingSenderId: '238114527059',
    projectId: 'daily-reminders-2a399',
    authDomain: 'daily-reminders-2a399.firebaseapp.com',
    storageBucket: 'daily-reminders-2a399.firebasestorage.app',
    measurementId: 'G-W82VXHNCBH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbbUCIuQ575EhBWOQoN16gKw5uJ2zkAu8',
    appId: '1:238114527059:ios:f1b4a4e6e05bc092b0b3a6',
    messagingSenderId: '238114527059',
    projectId: 'daily-reminders-2a399',
    storageBucket: 'daily-reminders-2a399.firebasestorage.app',
    iosBundleId: 'com.daily.reminders.flutterReminders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBev5NU_nXDfiuGRIz9sWi0xU-_h2XQT6g',
    appId: '1:238114527059:web:92a503b5e8c0408eb0b3a6',
    messagingSenderId: '238114527059',
    projectId: 'daily-reminders-2a399',
    authDomain: 'daily-reminders-2a399.firebaseapp.com',
    storageBucket: 'daily-reminders-2a399.firebasestorage.app',
    measurementId: 'G-G4X3TJ18PL',
  );
}
